version: '3.3'

services:
  web-service:
    container_name: web-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    ports:
      - 80:8080
    expose:
      - 80